### ISSUE TITLE
Epic: Set up dependencies

### ISSUE THREAD

**Issue by gnimnix** [NUS-Fintech-Society/Atlas_3_Frontend#7]
This serves as a test epic ticket.

- [ ] Set up CSS Assets #4 
- [ ] Set up React Query #5 
- [ ] Set up Mock Service Worker #6
